version: '2'

services:
  jira:
    image: openkunlun/confluence
    container_name: confluence
    ports:
       - '3090:8090'
       - '3091:8091'
  postgresql:
    image: postgres
    container_name: confluence_postgres
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_USER=openkunlun'
      - 'POSTGRES_PASSWORD=#a1a4*6DK'
      - 'POSTGRES_DB=kunlunconfluence'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
