version: '2'

services:
  confluence:
    image: openkunlun/docker-confluence:v6.3.4
    container_name: confluence
    ports:
       - '3090:8090'
      #  - '3091:8091'
    volumes:
      - /root/docker-volume/docker-confluence/:/var/atlassian/confluence
      - /root/docker-volume/docker-confluence/logs/:/opt/atlassian/confluence/logs